---
author: "Carl Boettiger"
institute: "UC Berkeley"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "solarized-light.css"]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: "solarized-light"
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(#dev.args=list(bg="transparent"), 
                      echo = FALSE, 
                      message=FALSE, 
                      warning=FALSE,
                      fig.width=11, 
                      fig.height=6.5, 
                      cache = TRUE)

library(tidyverse)
library(ggthemes)
theme_set(theme_solarized(base_size=22))
scale_colour_discrete <- function(...) scale_colour_solarized()
scale_fill_discrete <- function(...) scale_fill_solarized()
pal <- solarized_pal()(8)

txtcolor <- "#586e75"
```

layout: true
background-color: #fdf6e3
class: center, top

---

# My talk title here

## Subtitle H2

### H3

#### H4

##### H5 

Text with *emphasis*

<div class="my-footer">

<a href="https://carlboettiger.info"> `r icon::fa("user")` Carl Boettiger</a> | 
<a href="https://berkeley.edu"> `r icon::fa("briefcase")` UC Berkeley</a> | 
<a href="https://twitter.com/cboettig"> `r icon::fa("twitter")` @cboettig</a>

</div>

---

# First Slide

.pull-left[

- bulleted list
- the bullets are invisible
- that's nicer for centered text

]
.pull-right[

```{r fig.width=6, fig.height=4}
ggplot(mtcars, aes(cyl, mpg, fill=as.factor(cyl))) +
  geom_bar(stat="identity", show.legend = FALSE) + 
  ggtitle("Not mtcars again!")
```
]


---

# Second Slide